apiVersion: v1
kind: Service
metadata:
  name: ysmedi
  labels:
    app: ysmedi
    service.fastlane.co.kr/name: ysmedi
spec:
  ports:
    - name: http
      port: 10050
  selector:
    app: ysmedi
    service.fastlane.co.kr/name: ysmedi
